/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat_application.gui;

import chat_application.event.EventHandler;
import chat_application.chat_component.Body;
import chat_application.chat_component.Bottom;
import chat_application.chat_component.Title;
import chat_application.event.EventChat;
import chat_application.model.Recive_Message;
import chat_application.model.Send_Message;
import chat_application.model.User_Account;


import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Mikołaj
 */
public class Chat extends javax.swing.JPanel {

       private Title chatTitle;
    private Body chatBody;
    private Bottom chatBottom;
    public Chat() {
           init();
    }

    private void init() {
        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, bottom]0[shrink 0]0"));
        chatTitle = new Title();
        chatBody = new Body();
        chatBottom = new Bottom();
      EventHandler.getInstance().addEventChat(new EventChat() {
            @Override
            public void sendMessage(Send_Message data) {
                chatBody.addItemRight(data);
            }
             @Override
            public void receiveMessage(Recive_Message data) {
                if (chatTitle.getUser().getUserID() == data.getFromUserID()) {
                    chatBody.addItemLeft(data);
                }
            }
        });
        add(chatTitle, "wrap");
        add(chatBody, "wrap");
        add(chatBottom,"h ::50%");
    }
    public void setUser(User_Account user) {
     chatTitle.setUserName(user);
        chatBottom.setUser(user);
         chatBody.clearChat();
    }

    public void updateUser(User_Account user) {
        chatTitle.updateUser(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
